### ISSUE TITLE
Access log bucket creation fails during deployment

### ISSUE THREAD

**Issue by steveaitch** [aws-samples/document-translation#9]
Since the April changes to S3 bucket public access and ACLs, deployment now fails when creating serverAccessLogsBucket in pipeline-stack.ts and serverAccessLoggingBucket in doctran-stack.ts, giving "Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting" errors.

I have fixed this by adding `objectOwnership: s3.ObjectOwnership.OBJECT_WRITER,` to the properties when creating these buckets.

This is with version 1.1.3.

**Comment by philipws** [comment]
Hey @steveaitch thanks for raising this with us. I will take a look into it.

**Comment by giordafrancis** [comment]
I'm commenting here as I've experienced a similar deployment error and I've noticed this issue is now closed . When attempting to deploy the app I face the below error: 

_`Resource handler returned message: "Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: S3, Status Code: 400,`_

I've the latest version of the repo and both serverAccessLoggingBucket and serverAccessLogsBucket have the Object Ownership set to OBJECT_WRITER which should prevent this deployment  issue. 

Any idea on what is potential triggering the deployment error?

**Comment by philipws** [comment]
Hey @giordafrancis I believe I was asked about this by your AWS SA and it's been resolved. Can you confirm that's the case? (Or I've gotten you mixed up with someone else.

**Comment by giordafrancis** [comment]
> I'm commenting here as I've experienced a similar deployment error and I've noticed this issue is now closed . When attempting to deploy the app I face the below error:
> 
> _`Resource handler returned message: "Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: S3, Status Code: 400,`_
> 
> I've the latest version of the repo and both serverAccessLoggingBucket and serverAccessLogsBucket have the Object Ownership set to OBJECT_WRITER which should prevent this deployment issue.
> 
> Any idea on what is potential triggering the deployment error?

Just for reference this was this was fixed by using the latest tag to date (v2.2.0) merging with main, and then deploying the stack.

**Comment by giordafrancis** [comment]
> Hey @giordafrancis I believe I was asked about this by your AWS SA and it's been resolved. Can you confirm that's the case? (Or I've gotten you mixed up with someone else.

Yes! Thank you @philipws.  It was me and now it's resolved.  This was fixed by using the latest tag to date (v2.2.0) merging with main, and then deploying the stack.
